### ISSUE TITLE
Weird dark background in vim terminal buffers

### ISSUE THREAD

**Issue by victorkristof** [overcache/NeoSolarized#25]
Hi there,

Thanks for the great colorscheme!

I think there is an issue with the dark background for vim terminal buffers:
![terminal-dark](https://user-images.githubusercontent.com/3234366/89516701-10536f80-d7d9-11ea-8957-8d2623e8eb04.png)

On the right window, there is a terminal buffer opened with a `:terminal` command.
It looks greyish, which seems incorrect :)

Any idea what's happening?

Thanks!

**Comment by JonRoosevelt** [comment]
Same for me

**Comment by JonRoosevelt** [comment]
Just found out that you need to set termguicolors in your terminal.
In order to see if that works, just click esq and type set terminguicolors

If it works, then it's just a matter of adding it to your .vimrc or whatever it's your configurations. In my case, since I'm using nvim, it's on nvim/init.vim

**Comment by victorkristof** [comment]
Thanks for the suggestion! In my case, `:set temguicolors` doesn't work (it creates a colorless terminal, see `:h xterm-true-color`).

But for some reasons the problem disappeared by itself, and the colors of the vim terminal buffer are set correctly now (unrelated to `termguicolors`). Maybe a commit fixed this since August 2020?

Closing this issue for now!
